name: home_sm
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  # Bloc
  flutter_bloc: ^8.0.1
  # Utils
  equatable: ^0.2.0
  # Image
  flutter_svg: ^1.1.0
  # Router
  go_router: ^4.3.0




  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Auto gene
  freezed: ^2.0.5
  json_serializable: ^6.2.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/device/
    - assets/icons/navigation/


  fonts:
    - family: NotoSans
      fonts:
        # - asset: assets/fonts/NotoSants/NotoSans-Black.ttf
        # - asset: assets/fonts/NotoSants/NotoSans-BlackItalic.ttf
        #   style: italic
        - asset: assets/fonts/NotoSants/NotoSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSants/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSants/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSants/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSants/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSants/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSants/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSants/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSants/NotoSans-Black.ttf
          weight: 900
  
